# action.yml
name: 'Find Flags'
description: 'Test find flags'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  project:
    description: 'LaunchDarkly Project'
    required: true
    default: 'default'
  environment:
    description: 'LaunchDarkly Environment for Project'
    required: true
    default: 'prod'
